server:
  port: 8518
#spring boot 组件配置
spring:
  #redis
#  redis:
#    host: 192.168.155.150
#    port: 6379
#    password: Yixin4redis
  #dataSource
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/change_pet?serverTimezone=UTC&characterEncoding=utf-8&useSSL=true&autoReconnect=true
    username: root
    password: root
    druid:
      initial-size: 3
      min-idle: 1
      max-active: 20
      max-wait: 60000
      time-between-log-stats-millis: 300000
      time-between-eviction-runs-millis: 60000
      min-evictable-idle-time-millis: 300000
      max-pool-prepared-statement-per-connection-size: 20
      validation-query: SELECT 'x'
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false
      pool-prepared-statements: false
      filters: stat
      filter:
        stat:
          log-slow-sql: true
          slow-sql-millis: 10000
      stat-view-servlet:
        enabled: true
#mybatis
mybatis:
  mapper-locations: classpath:mappers/*Mapper.xml
  type-aliases-package: com.change.pet.entity
  #设置输出sql log
  configuration:
      log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
      map-underscore-to-camel-case: true


pagehelper:
  helper-dialect: mysql
  offset-as-page-num: true
  row-bounds-with-count: true
  pageSizeZero: true
  reasonable: true
  support-methods-arguments: true
  params: pageNum=pageNo;pageSize=pageSize;